;功能:从键盘输入1-4位十六进制数(它对应的二进制数
;是补码表示的带符号数),本程序将它转为带符号(+或-)
;的非压缩BCD码,并在屏幕上显示出来.


DATA SEGMENT
PROMPT DB 0AH,0DH
DB 'Input Hexdecimal(4 DIGITS):','$'
HEXBUF DB 5,0,5 DUP(0)
DISP DB 0AH,0DH
BCDBUF DB 6 DUP(0),'$'
DATA ENDS

STACK1 SEGMENT PARA STACK
DW 20H DUP(0)
STACK1 ENDS

COSEG SEGMENT
ASSUME CS:COSEG,DS:DATA,SS:STACK1
HEXBCD:
MOV AX,DATA
MOV DS,AX
;接受键盘输入的数据,放HEXBUF+2为首址的5个字节单元
; 其中,HEXBUF+1单元为输入的数据个数
LEA DX,PROMPT ;显示提示Input Hexdecimal(4 DIGITS):
MOV AH,09H
INT 21H
LEA DX,HEXBUF ;接受键盘输入
MOV AH,0AH
INT 21H
;把ASCII表示的1-4位十六进制数转为16位二进制数 放BX
LEA SI,HEXBUF+2 ;十六进制位数首地址
MOV BX,0 ;结果单元赋初值=0
MOV CH,HEXBUF+1 ;十六进制位数
HEX1:
MOV AL,[SI] ;取一位十六进制数
CMP AL,'9' ;与39H比较
JBE NUMB ;小于等于转（是数字转）
SUB AL,07H ;大于情况,-7（是字母）
NUMB:
AND AL,0FH
MOV CL,04
SAL BX,CL
OR BL,AL
INC SI
DEC CH
JNE HEX1
;BCD码单元清'0'
MOV WORD PTR BCDBUF+0,0
MOV WORD PTR BCDBUF+2,0
MOV WORD PTR BCDBUF+4,0
;确定十进制数（BCD码）的符号
MOV BCDBUF,'+'
TEST BX,8000H
JNS PLUS
MOV BCDBUF,'-'
NEG BX;取反
PLUS:
;从二进制数高位起,进行15次加和乘
MOV CH,0FH
LOP0:

CLC;进位标志设置为0
SHL BX,1;逻辑左移
CALL ADDIT
CALL MULTI
DEC CH
JNE LOP0
SHL BX,1
CALL ADDIT
;把非组合BCD码转变为ASCII码形式
LEA DI,BCDBUF+1
MOV CX,5
LOP1:
OR BYTE PTR [DI],30H
INC DI
LOOP LOP1
;显示转换结果
LEA DX,DISP
MOV AH,09H
INT 21H
;程序结束
MOV AH,4CH
INT 21H
