# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Vivado2019.2/zuchengyuanli/shiyan6/shiyan6.runs/synth_1/.Xil/Vivado-38064-DESKTOP-RIQG005/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a200tfbg676-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      D:/Vivado2019.2/zuchengyuanli/shiyan6/shiyan6.runs/synth_1/.Xil/Vivado-38064-DESKTOP-RIQG005/realtime/lcd_module_stub.v
      D:/Vivado2019.2/zuchengyuanli/source_code/6_single_cycle_cpu/adder.v
      D:/Vivado2019.2/zuchengyuanli/source_code/6_single_cycle_cpu/alu.v
      D:/Vivado2019.2/zuchengyuanli/source_code/6_single_cycle_cpu/data_ram.v
      D:/Vivado2019.2/zuchengyuanli/source_code/6_single_cycle_cpu/inst_rom.v
      D:/Vivado2019.2/zuchengyuanli/source_code/6_single_cycle_cpu/regfile.v
      D:/Vivado2019.2/zuchengyuanli/source_code/6_single_cycle_cpu/single_cycle_cpu.v
      D:/Vivado2019.2/zuchengyuanli/source_code/6_single_cycle_cpu/single_cycle_cpu_display.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList D:/Vivado2019.2/zuchengyuanli/shiyan6/shiyan6.runs/synth_1/.Xil/Vivado-38064-DESKTOP-RIQG005/realtime/single_cycle_cpu_display_synth.xdc
    rt::sdcChecksum
    set rt::top single_cycle_cpu_display
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {D:/Vivado2019.2/zuchengyuanli/shiyan6/shiyan6.cache/wt}
    rt::set_parameter enableSplitFlowPath "D:/Vivado2019.2/zuchengyuanli/shiyan6/shiyan6.runs/synth_1/.Xil/Vivado-38064-DESKTOP-RIQG005/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
