# Generated by Django 4.1.2 on 2023-03-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lwk", name="FBSJ", field=models.DateField(default="无"),
        ),
    ]
