# Generated by Django 4.1.2 on 2023-03-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_lwk_fbsj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lwk", name="FBSJ", field=models.TextField(default="无"),
        ),
    ]
