# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Vivado2019.2/zuchengyuanli/source_code/8_pipeline_cpu/pipeline_cpu.xdc

# IP: ip/inst_rom/inst_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==inst_rom || ORIG_REF_NAME==inst_rom} -quiet] -quiet
